"""Add is_deleted

Revision ID: 29533592fcde
Revises: 6ea65d165867
Create Date: 2025-04-08 11:35:05.221987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29533592fcde'
down_revision = '6ea65d165867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
