"""Eliminar columna notificado de Archivo

Revision ID: 496f325d9e1f
Revises: f7d06231d9ec
Create Date: 2025-04-01 12:28:50.593540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496f325d9e1f'
down_revision = 'f7d06231d9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.drop_column('notificado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificado', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
