"""Eliminar algunos campos de la tabla archivo

Revision ID: 71ae51b22e37
Revises: 496f325d9e1f
Create Date: 2025-04-01 12:32:39.496806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ae51b22e37'
down_revision = '496f325d9e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
