"""Crear tabla Income

Revision ID: c2bb0dd1b071
Revises: 65b57f0c8fd3
Create Date: 2025-04-05 16:42:44.097640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bb0dd1b071'
down_revision = '65b57f0c8fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
